// Spel-register. Lägg till ett nytt spel genom att importera dess modul och
// lägga det i GAMES — biblioteket och AssetService läser härifrån.
// Varje modul följer GameModule-kontraktet (se CLAUDE.md).
import klambubblor from './klambubblor/index.js'
import sorteraSkrap from './sortera-skrap/index.js'
import vandkort from './vandkort/index.js'
import poppaBallonger from './poppa-ballonger/index.js'
import tryckOchForvandla from './tryck-och-forvandla/index.js'
import kittlaFiguren from './kittla-figuren/index.js'
import fargregn from './fargregn/index.js'
import mataMonstret from './mata-monstret/index.js'
import raknaApplen from './rakna-applen/index.js'
import klappaMullvaden from './klappa-mullvaden/index.js'
import pekaPaKroppen from './peka-pa-kroppen/index.js'
import vilketDjurLater from './vilket-djur-later/index.js'
import storLiten from './stor-liten/index.js'
import tartaIAnsiktet from './tarta-i-ansiktet/index.js'
import klaPaNallen from './kla-pa-nallen/index.js'
import planteraFron from './plantera-fron/index.js'
import skuggmatchning from './skuggmatchning/index.js'
import enkeltPussel from './enkelt-pussel/index.js'
import plaskIVattnet from './plask-i-vattnet/index.js'
import klaEfterVadret from './kla-efter-vadret/index.js'
import vartTogDetVagen from './vart-tog-det-vagen/index.js'
import vadForsvann from './vad-forsvann/index.js'
import byggTornet from './bygg-tornet/index.js'
import rullaBollenHem from './rulla-bollen-hem/index.js'
import siffertaget from './siffertaget/index.js'
import sparaLinjen from './spara-linjen/index.js'
import harmaMelodin from './harma-melodin/index.js'
import foljSparet from './folj-sparet/index.js'
import studsbollar from './studsbollar/index.js'
import djurorkester from './djurorkester/index.js'
import studsaNer from './studsa-ner/index.js'
import fyrverkeri from './fyrverkeri/index.js'
import fangaFrukten from './fanga-frukten/index.js'
import vippbradan from './vippbradan/index.js'
import domino from './domino/index.js'
import studsmatta from './studsmatta/index.js'
import sapbubblor from './sapbubblor/index.js'
import knuffaTornet from './knuffa-tornet/index.js'
import spindelhjalten from './spindelhjalten/index.js'
import enhorningenElvira from './enhorningen-elvira/index.js'
import bajsOchKiss from './bajs-och-kiss/index.js'
import regnbagsmalaren from './regnbagsmalaren/index.js'
import pruttbad from './pruttbad/index.js'
import valpensBajs from './valpens-bajs/index.js'
import enhorningGlitterbajs from './enhorning-glitterbajs/index.js'
import tvattaDjuret from './tvatta-djuret/index.js'
import ballonglyft from './ballonglyft/index.js'
import gungan from './gungan/index.js'
import lagerelden from './lagerelden/index.js'
import spindelnatet from './spindelnatet/index.js'
import magnetFiske from './magnet-fiske/index.js'
import fallskarmen from './fallskarmen/index.js'
import enhorningenFlyger from './enhorningen-flyger/index.js'
import spindelZackeSvingar from './spindel-zacke-svingar/index.js'
import bowling from './bowling/index.js'
import flipperspel from './flipperspel/index.js'
import kulbana from './kulbana/index.js'
import snobollen from './snobollen/index.js'
import glasstornet from './glasstornet/index.js'
import golvetArLava from './golvet-ar-lava/index.js'
import vattenvagen from './vattenvagen/index.js'

export const GAMES = [klambubblor, sorteraSkrap, vandkort, poppaBallonger, tryckOchForvandla, kittlaFiguren, fargregn, mataMonstret, raknaApplen, klappaMullvaden, pekaPaKroppen, vilketDjurLater, storLiten, tartaIAnsiktet, klaPaNallen, planteraFron, skuggmatchning, enkeltPussel, plaskIVattnet, klaEfterVadret, vartTogDetVagen, vadForsvann, byggTornet, rullaBollenHem, siffertaget, sparaLinjen, harmaMelodin, foljSparet, studsbollar, djurorkester, studsaNer, fyrverkeri, fangaFrukten, vippbradan, domino, studsmatta, sapbubblor, knuffaTornet, spindelhjalten, enhorningenElvira, bajsOchKiss, regnbagsmalaren, pruttbad, valpensBajs, enhorningGlitterbajs, tvattaDjuret, ballonglyft, gungan, lagerelden, spindelnatet, magnetFiske, fallskarmen, enhorningenFlyger, spindelZackeSvingar, bowling, flipperspel, kulbana, snobollen, glasstornet, golvetArLava, vattenvagen]

export function getGame(id) {
  return GAMES.find((g) => g.id === id) || null
}
